Repository inspr/inspr, pull requests merged in 2021-06, with the labels that each got.

#70 Tech CORE-442 | Inspr CLI describe command outdated
  CHANGELOG.md
  pkg/meta/utils/format.go
  pkg/meta/utils/format_test.go
Labels: documentation

#73 Tech CORE-461 | Rename inspr CLI as insprctl
  CHANGELOG.md
  cmd/insprctl/cli/apply.go
  cmd/insprctl/cli/apply_alias.go
  cmd/insprctl/cli/apply_alias_test.go
  cmd/insprctl/cli/apply_channel.go
  cmd/insprctl/cli/apply_channel_test.go
  cmd/insprctl/cli/apply_channel_type.go
  cmd/insprctl/cli/apply_channel_type_test.go
  cmd/insprctl/cli/apply_dapp.go
  cmd/insprctl/cli/apply_dapp_test.go
  cmd/insprctl/cli/apply_factory.go
  cmd/insprctl/cli/apply_factory_test.go
  cmd/insprctl/cli/apply_test.go
  cmd/insprctl/cli/cli.go
  cmd/insprctl/cli/cli_test.go
  cmd/insprctl/cli/cluster.go
  cmd/insprctl/cli/cluster_test.go
  cmd/insprctl/cli/config_cmd.go
  cmd/insprctl/cli/config_cmd_test.go
  cmd/insprctl/cli/delete.go
  cmd/insprctl/cli/delete_test.go
  cmd/insprctl/cli/describe.go
  cmd/insprctl/cli/describe_test.go
  cmd/insprctl/cli/get.go
  cmd/insprctl/cli/get_test.go
  cmd/insprctl/cli/init.go
  cmd/insprctl/main.go
  docs/cli/main.go
  pkg/cmd/builder.go
  pkg/cmd/builder_test.go
  pkg/cmd/flags.go
  pkg/cmd/utils/cli_client.go
  pkg/cmd/utils/cli_client_test.go
Labels: cli, miscellaneous, tech pendency

#74 Tech CORE-430 | Refactor memory dApp section
  .github/scripts/update_tags.sh
  CHANGELOG.md
  cmd/insprd/memory/tree/dapp.go
  cmd/insprd/memory/tree/dapp_utils.go
  cmd/insprd/memory/tree/dapp_utils_test.go
  pkg/meta/utils/scope.go
Labels: documentation

#75 Story CORE-467 | Modify operator structure to handle multibrokers
  CHANGELOG.md
  build/uidp_helm/values.yaml
  cmd/insprd/main.go
  cmd/insprd/memory/brokers/brokers.go
  cmd/insprd/memory/brokers/brokers_test.go
  cmd/insprd/memory/brokers/interface.go
  cmd/insprd/memory/brokers/manager.go
  cmd/insprd/memory/brokers/manager_test.go
  cmd/insprd/memory/fake/broker_manager.go
  cmd/insprd/memory/fake/brokers.go
  cmd/insprd/memory/fake/factory.go
  cmd/insprd/memory/tree/dapp_utils.go
  cmd/insprd/memory/tree/dapp_utils_test.go
  cmd/insprd/operators/channel.go
  cmd/insprd/operators/interface.go
  cmd/insprd/operators/kafka/client.go
  cmd/insprd/operators/kafka/utils.go
  cmd/insprd/operators/operator.go
  cmd/sidecars/kafka.go
  pkg/api/handlers/brokers_handler.go
  pkg/api/handlers/brokers_handler_test.go
  pkg/api/models/brokers.go
  pkg/controller/client/brokers_test.go
  pkg/meta/brokers/brokers.go
  pkg/rest/middleware.go
Labels: controller, critical, documentation, enhancement, fix

#78 Bug CORE-475 | Deletion of multiple channels not working
  CHANGELOG.md
  build/uidp_helm/values.yaml
  cmd/insprctl/cli/cluster.go
  cmd/insprctl/cli/cluster_test.go
  cmd/insprctl/cli/delete.go
  cmd/insprctl/cli/delete_test.go
  cmd/insprd/memory/fake/mem_manager.go
  cmd/insprd/memory/interface.go
  cmd/insprd/memory/tree/alias.go
  cmd/insprd/memory/tree/channel.go
  cmd/insprd/memory/tree/dapp.go
  cmd/insprd/memory/tree/dapp_utils.go
  cmd/insprd/memory/tree/manager.go
  cmd/insprd/memory/tree/mock_manager.go
  cmd/insprd/memory/tree/types.go
  cmd/insprd/operators/channel.go
  cmd/insprd/operators/kafka/client.go
  cmd/insprd/operators/nodes/node_operator.go
  pkg/api/handlers/alias_handler.go
  pkg/api/handlers/app_handler.go
  pkg/api/handlers/channel_handler.go
  pkg/api/handlers/reactions.go
  pkg/api/handlers/token_handler.go
  pkg/api/handlers/type_handler.go
  pkg/cmd/flags.go
Labels: bug, documentation, fix

#33 Update networking from to v1, update k8s.io libs to v020.6
  CHANGELOG.md
  build/helm/templates/ingress.yaml
  build/helm/templates/pre-install-hook.yaml
  build/k8s/ingress.yaml
  build/k8s/insprd-dep.yaml
  build/k8s/insprd-svc.yaml
  build/uidp_helm/templates/ingress.yaml
  build/uidp_helm/values.yaml
  cmd/authsvc/secret/main.go
  cmd/insprd/operators/nodes/interfaces.go
  cmd/uid_provider/secret/main.go
  docs/pubsub.md
  examples/pubsub/k8s/ingress.yaml
  go.mod
  go.sum
Labels: documentation, enhancement, experimental, help wanted

#79 Story CORE-481 | docs yamls
  CHANGELOG.md
  docs/yamls/alias.md
  docs/yamls/channel.md
  docs/yamls/dapp.md
  docs/yamls/index.md
  docs/yamls/type.md
  examples/mbtest/kafkaConfig.yaml
Labels: documentation

#83 Story CORE-477 | troubleshooting.md
  CHANGELOG.md
  docs/troubleshooting.md
  examples/pingpong_demo/README.md
Labels: documentation

#81 Tech CORE-476 | Memory dependency refactor [Singletons]
  CHANGELOG.md
  build/uidp_helm/values.yaml
  cmd/insprctl/cli/cluster.go
  cmd/insprctl/cli/cluster_test.go
  cmd/insprd/main.go
  cmd/insprd/memory/brokers/brokers.go
  cmd/insprd/memory/brokers/brokers_test.go
  cmd/insprd/memory/brokers/interface.go
  cmd/insprd/memory/brokers/manager.go
  cmd/insprd/memory/brokers/manager_test.go
  cmd/insprd/memory/fake/alias.go
  cmd/insprd/memory/fake/broker_manager.go
  cmd/insprd/memory/fake/brokers.go
  cmd/insprd/memory/fake/channel.go
  cmd/insprd/memory/fake/dapp.go
  cmd/insprd/memory/fake/manager.go
  cmd/insprd/memory/fake/tree_manager.go
  cmd/insprd/memory/fake/type.go
  cmd/insprd/memory/interface.go
  cmd/insprd/memory/manager.go
  cmd/insprd/memory/tree/alias.go
  cmd/insprd/memory/tree/alias_test.go
  cmd/insprd/memory/tree/channel.go
  cmd/insprd/memory/tree/channel_test.go
  cmd/insprd/memory/tree/dapp.go
  cmd/insprd/memory/tree/dapp_test.go
  cmd/insprd/memory/tree/dapp_utils.go
  cmd/insprd/memory/tree/dapp_utils_test.go
  cmd/insprd/memory/tree/interface.go
  cmd/insprd/memory/tree/manager.go
  cmd/insprd/memory/tree/mock_app.go
  cmd/insprd/memory/tree/mock_channel.go
  cmd/insprd/memory/tree/mock_manager.go
  cmd/insprd/memory/tree/types.go
  cmd/insprd/memory/tree/types_test.go
  cmd/insprd/operators/channel.go
  cmd/insprd/operators/kafka/client.go
  cmd/insprd/operators/nodes/converter_test.go
  cmd/insprd/operators/nodes/node_operator.go
  cmd/insprd/operators/operator.go
  pkg/api/controllers/base.go
  pkg/api/controllers/base_test.go
  pkg/api/controllers/routes.go
  pkg/api/controllers/routes_test.go
  pkg/api/handlers/alias_handler.go
  pkg/api/handlers/alias_handler_test.go
  pkg/api/handlers/app_handler.go
  pkg/api/handlers/app_handler_test.go
  pkg/api/handlers/brokers_handler.go
  pkg/api/handlers/brokers_handler_test.go
  pkg/api/handlers/channel_handler.go
  pkg/api/handlers/channel_handler_test.go
  pkg/api/handlers/handler.go
  pkg/api/handlers/reactions.go
  pkg/api/handlers/type_handler.go
  pkg/api/handlers/type_handler_test.go
  pkg/api/models/brokers.go
  pkg/api/server.go
  pkg/client/client_test.go
  pkg/controller/client/brokers_test.go
Labels: controller, documentation
