Repository inspr/inspr, pull requests merged in 2021-05, with the labels that each got.

#40 Issue CORE-332 | adds a permissions field to the dApp definition
  CHANGELOG.md
Labels: documentation

#39 Issue CORE-336 | Alter the token to contain the permissions for each role and create the existant roles as an "enum"
  CHANGELOG.md
  build/uidp_helm/values.yaml
  cmd/authsvc/api/controllers/init.go
  cmd/authsvc/api/controllers/refresh.go
  cmd/authsvc/api/controllers/refresh_test.go
  cmd/authsvc/api/controllers/tokenize.go
  cmd/authsvc/api/controllers/tokenize_test.go
  cmd/insprd/operators/kafka/nodes/converter.go
  cmd/uid_provider/client/client.go
  cmd/uid_provider/client/client_test.go
  cmd/uid_provider/client/interface.go
  cmd/uid_provider/inprov/client/client_test.go
  cmd/uid_provider/inprov/cmd/create_user.go
  cmd/uid_provider/inprov/cmd/create_user_test.go
  cmd/uid_provider/inprov/user_example.yaml
  pkg/api/auth/payload.go
  pkg/api/controllers/routes_test.go
  pkg/api/handlers/token_handler.go
  pkg/auth/converter.go
  pkg/auth/interface.go
  pkg/auth/jwt/auth.go
  pkg/auth/jwt/auth_test.go
  pkg/auth/mocks/auth_mock.go
  pkg/auth/models.go
  pkg/auth/models/jwtDO.go
  pkg/auth/models/payload.go
  pkg/auth/models/refresh.go
  pkg/cmd/flags.go
  pkg/cmd/utils/cli_client.go
  pkg/controller/client/auth.go
  pkg/controller/client/auth_test.go
  pkg/controller/interface.go
  pkg/controller/mocks/auth.go
  pkg/rest/middleware.go
Labels: controller, documentation

#38 Feature/reactive sidecar
  CHANGELOG.md
  build/helm/templates/dep-insprd.yaml
  build/helm/values.yaml
  cmd/insprd/memory/tree/manager.go
  cmd/insprd/operators/kafka/nodes/converter.go
  cmd/insprd/operators/kafka/nodes/converter_test.go
  cmd/insprd/operators/kafka/nodes/k8s_variables.go
  cmd/insprd/operators/kafka/nodes/node_operator.go
  cmd/sidecars/kafka/client/mock_kafka.go
  cmd/sidecars/kafka/client/reader.go
  cmd/sidecars/kafka/client/reader_test.go
  cmd/sidecars/kafka/client/topic.go
  cmd/sidecars/kafka/client/writer.go
  cmd/sidecars/kafka/client/writer_test.go
  examples/multi_channel_demo/chcheck/Dockerfile
  examples/multi_channel_demo/chcheck/main.go
  examples/multi_channel_demo/chtest/Dockerfile
  examples/multi_channel_demo/chtest/main.go
  examples/multi_channel_demo/yamls/01.cht.yaml
  examples/pingpong_demo/ping/ping.go
  examples/pingpong_demo/pong/pong.go
  examples/primes/filter/main.go
  examples/primes/generator/main.go
  examples/primes/printer/main.go
  examples/pubsub/api/controller/base.go
  examples/pubsub/discord/main.go
  examples/pubsub/slack/main.go
  examples/sidecar_demo/sidecartest.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/interface.go
  pkg/environment/mocks.go
  pkg/environment/utils.go
  pkg/meta/dapp.go
  pkg/rest/request/request.go
  pkg/sidecar/models/interfaces.go
  pkg/sidecar/models/types.go
  pkg/sidecar/server/handlers.go
  pkg/sidecar/server/handlers_test.go
  pkg/sidecar/server/mocks.go
  pkg/sidecar/server/server.go
  pkg/sidecar/server/server_test.go
  pkg/sidecar/transports/unix.go
  pkg/sidecar/transports/unix_test.go
Labels: build, controller, documentation, enhancement

#41 Issue CORE-338 | Alter the authorization middleware to handle invalid requests
  CHANGELOG.md
  cmd/inspr/cli/delete_test.go
  cmd/uid_provider/client/client_test.go
  examples/master_demo/main.go
  pkg/api/handlers/alias_handler.go
  pkg/api/handlers/alias_handler_test.go
  pkg/api/handlers/app_handler.go
  pkg/api/handlers/app_handler_test.go
  pkg/api/handlers/channel_handler.go
  pkg/api/handlers/channel_handler_test.go
  pkg/api/handlers/channel_type_handler.go
  pkg/api/handlers/channel_type_handler_test.go
  pkg/api/models/alias.go
  pkg/api/models/channel.go
  pkg/api/models/channel_type.go
  pkg/api/models/dapp.go
  pkg/auth/jwt/auth.go
  pkg/auth/mocks/auth_mock.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/controller/client/alias.go
  pkg/controller/client/alias_test.go
  pkg/controller/client/auth.go
  pkg/controller/client/auth_test.go
  pkg/controller/client/channel.go
  pkg/controller/client/channel_test.go
  pkg/controller/client/channel_type.go
  pkg/controller/client/channel_type_test.go
  pkg/controller/client/client.go
  pkg/controller/client/dapp.go
  pkg/controller/client/dapp_test.go
  pkg/environment/mocks.go
  pkg/rest/constants.go
  pkg/rest/middleware.go
  pkg/rest/middleware_test.go
  pkg/rest/request/builder.go
  pkg/rest/request/client.go
  pkg/rest/request/client_test.go
  pkg/rest/request/request.go
  pkg/rest/request/request_test.go
Labels: controller, documentation

#45 Story CORE-291 | Authentication roles
  CHANGELOG.md
  cmd/inspr/cli/delete_test.go
  cmd/insprd/operators/kafka/nodes/node_operator_test.go
  cmd/uid_provider/client/client_test.go
  examples/master_demo/main.go
  pkg/api/handlers/alias_handler.go
  pkg/api/handlers/alias_handler_test.go
  pkg/api/handlers/app_handler.go
  pkg/api/handlers/app_handler_test.go
  pkg/api/handlers/channel_handler.go
  pkg/api/handlers/channel_handler_test.go
  pkg/api/handlers/channel_type_handler.go
  pkg/api/handlers/channel_type_handler_test.go
  pkg/api/models/alias.go
  pkg/api/models/channel.go
  pkg/api/models/channel_type.go
  pkg/api/models/dapp.go
  pkg/auth/jwt/auth.go
  pkg/auth/mocks/auth_mock.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/controller/client/alias.go
  pkg/controller/client/alias_test.go
  pkg/controller/client/auth.go
  pkg/controller/client/auth_test.go
  pkg/controller/client/channel.go
  pkg/controller/client/channel_test.go
  pkg/controller/client/channel_type.go
  pkg/controller/client/channel_type_test.go
  pkg/controller/client/client.go
  pkg/controller/client/dapp.go
  pkg/controller/client/dapp_test.go
  pkg/environment/mocks.go
  pkg/rest/constants.go
  pkg/rest/middleware.go
  pkg/rest/middleware_test.go
  pkg/rest/request/builder.go
  pkg/rest/request/client.go
  pkg/rest/request/client_test.go
  pkg/rest/request/request.go
  pkg/rest/request/request_test.go
Labels: controller, documentation

#44 Issue CORE-333 | Create the token for authentication inside the cluster
  CHANGELOG.md
  build/helm/templates/dep-insprd.yaml
  build/helm/templates/kafka-configmap.yaml
  build/helm/templates/sidecar-configmap.yaml
  build/helm/values.yaml
  build/uidp_helm/values.yaml
  cmd/inspr/cli/auth_init.go
  cmd/insprd/main.go
  cmd/insprd/operators/kafka/nodes/converter.go
  cmd/insprd/operators/kafka/nodes/converter_test.go
  cmd/insprd/operators/kafka/nodes/interfaces.go
  cmd/insprd/operators/kafka/nodes/node_operator.go
  cmd/insprd/operators/kafka/nodes/node_operator_test.go
  cmd/insprd/operators/kafka/operator.go
  cmd/insprd/operators/node.go
  examples/k8s_op_demo/main.go
  pkg/api/controllers/routes.go
  pkg/api/handlers/token_handler.go
  pkg/client/client.go
  pkg/environment/environment.go
  pkg/environment/environment_test.go
  pkg/operator/k8s/container.go
  pkg/operator/k8s/deployment.go
  pkg/operator/k8s/deployment_test.go
  pkg/sidecar/server/server.go
  skaffold.yaml
Labels: build, documentation

#48 Feature: adds init command for config initialization
  CHANGELOG.md
  cmd/inspr/cli/apply.go
  cmd/inspr/cli/apply_test.go
  cmd/inspr/cli/cli.go
  cmd/inspr/cli/cli_test.go
  cmd/inspr/cli/config_cmd.go
  cmd/inspr/cli/config_cmd_test.go
  cmd/inspr/cli/init.go
  cmd/uid_provider/inprov/cmd/create_user.go
  cmd/uid_provider/inprov/cmd/delete_usr.go
  cmd/uid_provider/inprov/cmd/login.go
  pkg/cmd/builder.go
  pkg/cmd/builder_test.go
  pkg/cmd/constants.go
  pkg/cmd/flags.go
  pkg/cmd/utils/cli_client.go
  pkg/cmd/utils/cli_client_test.go
  pkg/cmd/utils/viper.go
  pkg/cmd/utils/viper_test.go
  pkg/rest/request/request.go
Labels: documentation

#52 Bug CORE-425 | Check failing controller update method
  CHANGELOG.md
  \
  build/uidp_helm/values.yaml
  examples/controller/main.go
  examples/controller/yamls/ingress.yaml
Labels: controller, documentation

#53 Tech CORE-362 | Validate alias when applying app
  CHANGELOG.md
  cmd/insprd/memory/tree/dapp_utils.go
  cmd/insprd/memory/tree/dapp_utils_test.go
Labels: documentation

#54 Tech CORE-365 | Alias Meta.Name automatic injection when applying app
  CHANGELOG.md
  build/uidp_helm/values.yaml
  cmd/inspr/cli/apply_dapp.go
  cmd/inspr/cli/apply_dapp_test.go
  cmd/inspr/cli/describe.go
  cmd/inspr/cli/describe_test.go
  cmd/inspr/cli/get_test.go
  cmd/uid_provider/inprov/user_example.yaml
  pkg/cmd/utils/process_args.go
  pkg/cmd/utils/process_args_test.go
  pkg/meta/utils/parser/dapp_yaml.go
  pkg/meta/utils/parser/dapp_yaml_test.go
  pkg/meta/utils/scope.go
  pkg/meta/utils/scope_test.go
  pkg/meta/utils/structure_names.go
  pkg/meta/utils/structure_names_test.go
Labels: documentation

#56 Story CORE-417 | Create a broker-tracking structure
  CHANGELOG.md
  cmd/insprd/memory/fake/brokers.go
  cmd/insprd/memory/fake/mem_manager.go
  cmd/insprd/memory/interface.go
  cmd/insprd/memory/tree/brokers.go
  cmd/insprd/memory/tree/brokers_test.go
  cmd/insprd/memory/tree/manager.go
  pkg/meta/brokers/brokers.go
  pkg/meta/utils/str_set.go
  pkg/meta/utils/str_set_test.go
Labels: documentation

#55 Tech CORE-310 | Automatic Helm chart tags update
  .github/scripts/pushcli.sh
  .github/scripts/releasecli.sh
  .github/workflows/release.yml
  .gitignore
  CHANGELOG.md
Labels: documentation

#59 Fix: CORE-310 | Automatic Helm chart tags update
  .github/workflows/release.yml
  CHANGELOG.md
Labels: documentation

#57 Tech CORE-426 | Review Permissions
  CHANGELOG.md
  build/uidp_helm/values.yaml
  cmd/inspr/cli/get.go
  cmd/inspr/cli/get_test.go
  cmd/uid_provider/api/handlers/handler_test.go
  cmd/uid_provider/client/client.go
  cmd/uid_provider/client/client_test.go
  pkg/meta/utils/scope.go
  pkg/meta/utils/scope_test.go
Labels: documentation

#58 Story CORE-418 | Create Sidecar Factory
  CHANGELOG.md
  cmd/insprd/memory/brokers/brokers.go
  cmd/insprd/memory/brokers/brokers_test.go
  cmd/insprd/memory/brokers/factory.go
  cmd/insprd/memory/brokers/factory_test.go
  cmd/insprd/memory/brokers/interface.go
  cmd/insprd/memory/brokers/manager.go
  cmd/insprd/memory/brokers/manager_test.go
  cmd/insprd/memory/fake/broker_manager.go
  cmd/insprd/memory/fake/brokers.go
  cmd/insprd/memory/fake/factory.go
  cmd/insprd/memory/fake/mem_manager.go
  cmd/insprd/memory/interface.go
  pkg/sidecar/models/factory.go
Labels: documentation

#61 Story CORE-428 | CLI get installed brokers command
  CHANGELOG.md
  build/helm/templates/ingress.yaml
  build/uidp_helm/values.yaml
  cmd/inspr/cli/auth_init.go
  cmd/inspr/cli/cli.go
  cmd/inspr/cli/get_brokers.go
  cmd/insprd/main.go
  cmd/insprd/memory/brokers/brokers.go
  cmd/insprd/memory/brokers/brokers_test.go
  cmd/insprd/memory/brokers/interface.go
  cmd/insprd/memory/fake/broker_manager.go
  cmd/insprd/memory/fake/brokers.go
  pkg/api/controllers/base.go
  pkg/api/controllers/base_test.go
  pkg/api/controllers/routes.go
  pkg/api/handlers/alias_handler_test.go
  pkg/api/handlers/app_handler_test.go
  pkg/api/handlers/brokers_handler.go
  pkg/api/handlers/brokers_handler_test.go
  pkg/api/handlers/channel_handler_test.go
  pkg/api/handlers/handler.go
  pkg/api/handlers/type_handler_test.go
  pkg/api/models/brokers.go
  pkg/api/server.go
  pkg/controller/client/brokers.go
  pkg/controller/client/brokers_test.go
  pkg/controller/client/client.go
  pkg/controller/interface.go
  pkg/controller/mocks/brokers.go
  pkg/controller/mocks/client.go
Labels: api, controller, documentation

#62 Story CORE-413 | Modify Channel structure
  CHANGELOG.md
  cmd/insprd/memory/brokers/manager.go
  cmd/insprd/memory/brokers/models.go
  cmd/insprd/memory/tree/channel.go
  cmd/insprd/memory/tree/dapp_utils.go
  cmd/insprd/memory/tree/dapp_utils_test.go
  pkg/meta/channel.go
Labels: documentation

#64 Tech CORE-448 | Unification of `inspr cluster` commands
  CHANGELOG.md
  cmd/inspr/cli/auth_init.go
  cmd/inspr/cli/cli.go
  cmd/inspr/cli/cluster.go
  cmd/inspr/cli/cluster_test.go
  cmd/inspr/cli/delete.go
  cmd/inspr/cli/describe.go
  cmd/inspr/cli/get.go
  cmd/inspr/cli/get_brokers.go
  pkg/cmd/builder.go
  pkg/cmd/builder_test.go
Labels: documentation

#60 Story CORE-419 | Create Kafka sidecar Factory
  CHANGELOG.md
  cmd/insprd/operators/kafka/nodes/converter.go
  cmd/sidecars/kafka.go
  cmd/sidecars/kafka_test.go
  cmd/sidecars/utils.go
  cmd/sidecars/utils_test.go
Labels: documentation

#63 Story CORE-414 | Adapt the current sidecar to a load balancer sidecar
  CHANGELOG.md
  build/helm/templates/dep-insprd.yaml
  build/helm/templates/sidecar-configmap.yaml
  build/helm/values.yaml
  cmd/insprd/Dockerfile.dockerignore
  cmd/insprd/memory/brokers/factory.go
  cmd/insprd/memory/brokers/factory_test.go
  cmd/insprd/memory/brokers/interface.go
  cmd/insprd/memory/fake/factory.go
  cmd/insprd/memory/interface.go
  cmd/insprd/memory/tree/mock_manager.go
  cmd/insprd/operators/kafka/nodes/converter.go
  cmd/insprd/operators/kafka/nodes/converter_test.go
  cmd/sidecars/kafka.go
  cmd/sidecars/kafka/client/reader.go
  cmd/sidecars/kafka/client/topic.go
  cmd/sidecars/kafka/main.go
  cmd/sidecars/kafka_test.go
  cmd/sidecars/lbsidecar/.dockerignore
  cmd/sidecars/lbsidecar/Dockerfile
  cmd/sidecars/lbsidecar/main.go
  docs/workspace_init.md
  examples/multi_channel_demo/chcheck/main.go
  examples/multi_channel_demo/chtest/main.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/environment/environment.go
  pkg/environment/environment_test.go
  pkg/environment/mocks.go
  pkg/meta/dapp.go
  pkg/sidecar_old/models/factory.go
  pkg/sidecar_old/models/interfaces.go
  pkg/sidecar_old/models/types.go
  pkg/sidecar_old/server/handlers.go
  pkg/sidecar_old/server/handlers_test.go
  pkg/sidecar_old/server/server.go
  pkg/sidecar_old/server/server_test.go
  pkg/sidecars/lbsidecar/avrocodec.go
  pkg/sidecars/lbsidecar/handlers.go
  pkg/sidecars/lbsidecar/handlers_test.go
  pkg/sidecars/lbsidecar/server.go
  pkg/sidecars/lbsidecar/server_test.go
  pkg/sidecars/models/factory.go
  pkg/sidecars/models/interfaces.go
  pkg/sidecars/models/types.go
Labels: api, blocking, build, critical, documentation

#67 Tech CORE-429 | Change the inspr cmd cluster command to ignore the .inspr/token
  CHANGELOG.md
  build/uidp_helm/values.yaml
  cmd/uid_provider/client/client.go
  pkg/auth/models.go
  pkg/controller/client/auth.go
Labels: controller, documentation

#68 Bugfix CORE-431 | UIDP Refresh token crash
  CHANGELOG.md
  build/uidp_helm/values.yaml
  cmd/authsvc/api/controllers/base.go
  cmd/authsvc/api/controllers/init.go
  cmd/authsvc/api/controllers/refresh.go
  cmd/authsvc/api/controllers/refresh_test.go
  cmd/authsvc/api/controllers/tokenize.go
  cmd/authsvc/api/controllers/tokenize_test.go
  cmd/insprd/memory/brokers/brokers.go
  cmd/insprd/memory/fake/brokers.go
  cmd/sidecars/kafka.go
  cmd/uid_provider/api/handlers/handler_test.go
  cmd/uid_provider/client/client_test.go
  cmd/uid_provider/inprov/client/client.go
  cmd/uid_provider/inprov/client/client_test.go
  cmd/uid_provider/inprov/user_example.yaml
  examples/controller/.dockerignore
  examples/controller/main.go
  examples/controller/yamls/ingress.yaml
  examples/primes/yamls/pingpong.go
  pkg/auth/jwt/auth.go
  pkg/auth/rsa-from-env.go
  pkg/client/client_test.go
  pkg/controller/client/alias.go
  pkg/controller/client/alias_test.go
  pkg/controller/client/auth.go
  pkg/controller/client/auth_test.go
  pkg/controller/client/brokers.go
  pkg/controller/client/brokers_test.go
  pkg/controller/client/channel.go
  pkg/controller/client/channel_test.go
  pkg/controller/client/dapp.go
  pkg/controller/client/dapp_test.go
  pkg/controller/client/type.go
  pkg/controller/client/type_test.go
  pkg/meta/utils/diff/diff.go
  pkg/operator/k8s/container.go
  pkg/rest/constants.go
  pkg/rest/middleware.go
  pkg/rest/middleware_test.go
  pkg/rest/request/request_test.go
  pkg/sidecar_old/server/handlers_test.go
  pkg/sidecars/lbsidecar/handlers.go
Labels: bug, controller, documentation, fix, refactor
