Repository inspr/inspr, pull requests merged in 2021-04, with the labels that each got.

#7 Update README.md
  .gitignore
  README.md
  docs/img/logo.png
  docs/img/logo@2x.png
  docs/img/logo@3x.png
Labels: documentation

#17 CORE-342 Integration | Story 288 build and dependencies corrections
  cmd/insprd/Dockerfile.dockerignore
  cmd/insprd/api/handlers/handler.go
  cmd/sidecars/kafka/Dockerfile.dockerignore
  pkg/auth/interface.go
  pkg/auth/jwt/auth.go
  pkg/auth/jwt/auth_test.go
  pkg/auth/mocks/auth_mock.go
  pkg/rest/middleware.go
  pkg/rest/middleware_test.go
Labels: cmd@insprd

#21 Issue CORE-299 | Wrapping routes in auth layer
  cmd/authsvc/secret/main.go
  cmd/authsvc/secret/main_test.go
  cmd/insprd/api/controllers/base.go
  cmd/insprd/api/controllers/base_test.go
  cmd/insprd/api/controllers/routes.go
  cmd/insprd/api/controllers/routes_test.go
  cmd/insprd/api/handlers/alias_handler_test.go
  cmd/insprd/api/handlers/app_handler.go
  cmd/insprd/api/handlers/app_handler_test.go
  cmd/insprd/api/handlers/channel_handler_test.go
  cmd/insprd/api/handlers/channel_type_handler_test.go
  cmd/insprd/api/handlers/handler.go
  cmd/insprd/api/handlers/token_handler.go
  cmd/insprd/api/server.go
  cmd/insprd/main.go
  pkg/auth/rsa-from-env.go
  pkg/auth/rsa-from-env_test.go
  pkg/rest/middleware.go
Labels: api, cmd@insprd

#14 TASK CORE-358 | update readme to open source
  README.md
  docs/dapp_overview.md
  docs/img/chan-func.png
  docs/img/dapp-compose.png
  docs/img/dapp-comunication.png
  docs/img/dapp-struct.png
  docs/img/dapp-tree.jpg
  docs/img/dapp-tree.png
  docs/readme-structure.md
Labels: documentation

#29 Update README adding the website URL and images
  .gitignore
  README.md
  docs/img/dapp-communication.png
Labels: documentation

#24 Issue CORE-307 and CORE-326 | Adds token to the controller client
  LICENSE-docs.md
  README.md
  cmd/inspr/cli/apply.go
  cmd/inspr/cli/apply_alias.go
  cmd/inspr/cli/apply_alias_test.go
  cmd/inspr/cli/apply_channel.go
  cmd/inspr/cli/apply_channel_test.go
  cmd/inspr/cli/apply_channel_type.go
  cmd/inspr/cli/apply_channel_type_test.go
  cmd/inspr/cli/apply_dapp.go
  cmd/inspr/cli/apply_dapp_test.go
  cmd/inspr/cli/apply_test.go
  cmd/inspr/cli/cli.go
  cmd/inspr/cli/cli_test.go
  cmd/inspr/cli/config_cmd.go
  cmd/inspr/cli/config_cmd_test.go
  cmd/inspr/cli/delete.go
  cmd/inspr/cli/delete_test.go
  cmd/inspr/cli/describe.go
  cmd/inspr/cli/describe_test.go
  cmd/inspr/cli/get.go
  cmd/inspr/cli/get_test.go
  cmd/inspr/main.go
  cmd/uid_provider/client/client.go
  codecov.yml
  pkg/cmd/constants.go
  pkg/cmd/flags.go
  pkg/cmd/utils/cli_client.go
  pkg/cmd/utils/get_scope.go
  pkg/cmd/utils/get_scope_test.go
  pkg/cmd/utils/get_token.go
  pkg/cmd/utils/process_args.go
  pkg/cmd/utils/process_args_test.go
  pkg/cmd/utils/test/viper_config
  pkg/cmd/utils/viper.go
  pkg/cmd/utils/viper_test.go
  pkg/controller/client/client.go
  pkg/controller/client/client_test.go
  pkg/rest/request/builder.go
  pkg/rest/request/request.go
Labels: documentation

#20 fix: remove gitlab references
  .github/scripts/update_tags.sh
  .gitlab-ci.yml
  docs/cli_install.md
Labels: enhancement, invalid
